import { useEffect, useMemo, useRef, useState } from "react";
import { trpc } from "@/lib/trpc";
import { ArrowDown, ArrowLeft, ArrowRight, Check, Heart, LockKeyhole, Music2, Unlock, Pause, Play, Sparkles, Volume2, VolumeX, X } from "lucide-react";
import { cycleGalleryIndex, futureHopeLines, unlockProgress } from "./Home.logic";

const memories = [
  { kind: "feature", label: "HERO_IMAGE", title: "Our favourite picture", caption: "", tone: "rose", image: "/our-favourite-picture.jpeg" },
  { kind: "photo", label: "lami-01.jpg", title: "My Sugar", caption: "One of my favourite smiles.", tone: "blush", image: "/my-sugar.jpeg" },
  { kind: "photo", label: "us-01.jpg", title: "Just us", caption: "The ordinary moments are never ordinary with you.", tone: "gold", image: "/just-us.jpeg" },
  { kind: "video", label: "video-01.mp4", title: "A little moving memory", caption: "A little piece of us, in motion.", tone: "wine", image: "/a-little-loving-memory.mp4" },
  { kind: "photo", label: "memory-01.jpg", title: "Still beautiful", caption: "Effortlessly, always.", tone: "ink", image: "/still-beautiful.jpeg" },
  { kind: "photo", label: "lami-02.jpg", title: "Look at my girl", caption: "How are you this fine?", tone: "plum", image: "/look-at-my-girl.jpeg" },
  { kind: "photo", label: "memory-02.jpg", title: "A day to keep", caption: "One of those frames I want to keep close.", tone: "rose", image: "/hero-image.jpeg" },
];
const loveNotes = [["01", "Your smile", "You smile so beautifully."], ["02", "The way you smell", "Honestly, Sugar… how do you always smell this good?"], ["03", "Your intelligence", "You're genuinely intelligent, and I admire that about you."], ["04", "Your voice", "I love hearing you talk."], ["05", "The way you sing", "You sing so beautifully."], ["06", "You're a keeper", "And somehow, this is still only a small list."]];
function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p>; }
function Reveal({ children }: { children: React.ReactNode }) { return <span className="reveal-line">{children}</span>; }

export default function Home() {
  const [unlocked, setUnlocked] = useState(() => localStorage.getItem("isUnlocked") === "true"), [welcome, setWelcome] = useState(false), [intro, setIntro] = useState(true), [passcode, setPasscode] = useState(""), [wrong, setWrong] = useState(false), [secretError, setSecretError] = useState(false), [revealedMove, setRevealedMove] = useState(false), [loveIndex, setLoveIndex] = useState(0), [galleryIndex, setGalleryIndex] = useState<number | null>(null), [hungry, setHungry] = useState(false), [oko, setOko] = useState(false), [baby, setBaby] = useState(false), [isPlaying, setIsPlaying] = useState(false), [isMuted, setIsMuted] = useState(false);
  const audioRef = useRef<HTMLAudioElement>(null);
  
  useEffect(() => {
    if (audioRef.current) {
      if (isPlaying) {
        audioRef.current.play().catch(e => console.error("Autoplay blocked:", e));
      } else {
        audioRef.current.pause();
      }
    }
  }, [isPlaying]);

  useEffect(() => {
    if (audioRef.current) {
      audioRef.current.muted = isMuted;
    }
  }, [isMuted]);
  const verify = { isFetching: false };
  const progress = useMemo(() => Math.round(((loveIndex + 1) / loveNotes.length) * 100), [loveIndex]);
  const lightboxCloseRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (galleryIndex === null) return; lightboxCloseRef.current?.focus(); const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") setGalleryIndex(null); if (event.key === "ArrowRight") setGalleryIndex(index => index === null ? 0 : cycleGalleryIndex(index, 1, memories.length)); if (event.key === "ArrowLeft") setGalleryIndex(index => index === null ? 0 : cycleGalleryIndex(index, -1, memories.length)); }; window.addEventListener("keydown", onKey); document.body.style.overflow = "hidden"; return () => { window.removeEventListener("keydown", onKey); document.body.style.overflow = ""; }; }, [galleryIndex]);
  const unlock = async (event: React.FormEvent) => { event.preventDefault(); setWrong(false); setSecretError(false); if (!passcode.trim()) return; try { const valid = passcode === (import.meta.env.VITE_UNLOCK_CODE || "1234"); if (valid && unlockProgress(true) === "welcome") { setUnlocked(true); setWelcome(true); localStorage.setItem("isUnlocked", "true"); } else setWrong(true); } catch { setSecretError(true); } };
  if (!unlocked) return <main className="entrance"><div className="grain" /><div className="entrance-orbit orbit-one" /><div className="entrance-orbit orbit-two" /><div className="entrance-card"><div className="seal"><LockKeyhole size={22} strokeWidth={1.5} /></div><SectionLabel>Private · For Lami only</SectionLabel><h1>Some things are<br /><em>meant only for you.</em></h1><p className="entrance-copy">A little place made from the memories, laughter, and love we have collected together.</p><form onSubmit={unlock} className="pass-form"><label htmlFor="passcode">Enter your secret code</label><div className="pass-row"><input id="passcode" type="password" autoComplete="off" value={passcode} onChange={e => setPasscode(e.target.value)} placeholder="Your secret code" aria-describedby="pass-status" /><button className="gold-button" type="submit" disabled={verify.isFetching}>Unlock <ArrowRight size={16} /></button></div></form><div id="pass-status" role="status" aria-live="polite" className={wrong || secretError ? "error-copy" : "hint-copy"}>{wrong ? "Not quite, Babe. Try again — I know you know it. ❤️" : secretError ? "The lock needs a moment. Please try again." : "A door into our little world."}</div></div></main>;
  if (welcome) return <main className="intro unlock-welcome"><div className="grain" /><div className="intro-copy"><div className="seal"><Unlock size={22} strokeWidth={1.5} /></div><p className="eyebrow">The lock is open</p><h1>Welcome, <em>Lami</em> <Heart fill="currentColor" size={24} /></h1><p>I've been waiting for you.</p><button className="heart-button" onClick={() => setWelcome(false)} aria-label="Continue into the anniversary experience"><ArrowRight size={25} /><span>Enter our story</span></button></div></main>;
  if (intro) return <main className="intro"><div className="grain" /><div className="intro-copy"><p className="eyebrow">A note from Timi</p><h1>For the girl who<br /><em>started as a friend…</em></h1><p>…and somehow became my favourite person.</p><button className="heart-button" onClick={() => { setIntro(false); setIsPlaying(true); }} aria-label="Enter the anniversary experience"><Heart fill="currentColor" size={25} /><span>Tap the heart</span></button><p className="intro-signoff">Olamide mi . My Sugar . My Babyyy.</p></div></main>;
  return <div className="site-shell"><div className="grain" /><header className="site-nav"><a href="#top" className="wordmark">Timi <span>×</span> Lami</a><nav><a href="#story">Our story</a><a href="#memories">Memories</a><a href="#letter">A letter</a></nav><a href="#ending" className="nav-cta">07·09·26 <ArrowDown size={14} /></a></header><main id="top">
    <section className="hero section-dark"><div className="hero-watermark">01</div><div className="hero-copy"><SectionLabel>Our first anniversary · September 7, 2026</SectionLabel><h1>Happy 1st<br /><em>Anniversary,</em><br /><span>Lami <Heart fill="currentColor" size={28} /></span></h1><p className="hero-sub">One year of choosing you.<br />A lifetime I hope we get to build.</p><a className="scroll-cue" href="#story"><span>Scroll to our story</span><ArrowDown size={15} /></a></div><div className="hero-art"><div className="hero-placeholder has-photo"><img src="/our-favourite-picture.jpeg" className="w-full h-full object-cover absolute inset-0" alt="Timi and Lami together, smiling at the camera" /><div className="hero-photo-caption"><span></span><strong>Your favourite photo of us</strong><small></small></div></div><div className="hero-stamp">01<br /><span>year<br />of us</span></div></div></section>
    <section id="story" className="section-light story"><div className="section-intro"><SectionLabel>Before there was us…</SectionLabel><h2>The long way<br /><em>to here.</em></h2><p>Some of the best things take their time. Ours started quietly, as friendship, then found its way home.</p></div><div className="timeline"><article className="timeline-item"><div className="timeline-year">2021</div><div><h3>The beginning</h3><p>We met at <strong>Glory Arena, Redemption City.</strong> We were friends.</p><blockquote>“We didn't know it then, but that meeting would eventually become the beginning of something much bigger.”</blockquote></div></article><article className="timeline-item"><div className="timeline-year">2023</div><div><h3>The cinema date <span>😂</span></h3><div className="plan-grid"><div><small>The plan</small><p>Afternoon cinema date.</p></div><div><small>Reality</small><p>Lami came late. 😂</p></div><div><small>The result</small><p>Late-night movie + first cinema experience + one unforgettable memory.</p></div></div><p className="timeline-note">After three weeks of compulsory NYSC camping, we went to see <strong>A Tribe Called Judah.</strong> It was Timi's first time at a cinema.</p></div></article></div></section>
    <section className="move-section section-wine"><div className="section-center"><SectionLabel>A question for the record</SectionLabel><h2>Who made<br /><em>the first move?</em></h2><div className="choice-row"><button onClick={() => setRevealedMove(false)}>Lami <Heart size={15} fill="currentColor" /></button><button onClick={() => setRevealedMove(true)}>Timi <span>😌</span></button></div>{revealedMove && <div className="reveal-card" role="status"><Check size={17} /><p><strong>Yes, I did. 😂</strong><br />Unfortunately, you didn't take me seriously. You left me comfortably sitting in the friend zone. And somehow, after all those years… look at us now.</p></div>}</div></section>
    <section className="night section-dark"><div className="night-glow" /><div className="section-center"><SectionLabel>September 6, 2025</SectionLabel><h2>The night before<br /><em>you said yes.</em></h2><div className="night-copy"><p>We went to Redemption City together. We left camp that night and somehow ended up trekking.</p><p>It wasn't some expensive date. It wasn't perfectly planned. <strong>It was just us.</strong></p><p>And somehow, that ordinary night became one of my favourite memories.</p></div><div className="pause-line"><span>Because the next day…</span><strong>Everything changed.</strong></div></div></section>
    <section className="yes-section section-light"><SectionLabel>September 7, 2025</SectionLabel><h2>After years of friendship…<br /><em>you finally said yes.</em></h2><div className="yes-mark"><Heart fill="currentColor" size={36} /><p>My friend became my girl.</p></div><p className="yes-foot">A quiet yes. A very big beginning.</p></section>
    <section id="memories" className="gallery-section section-cream"><div className="section-intro gallery-intro"><div><SectionLabel>One year of us</SectionLabel><h2>Little frames<br /><em>of a big feeling.</em></h2></div><p>A few frames from our year. The story is already here; the pictures make it ours.</p></div><div className="gallery-grid">{memories.map((memory, i) => <button key={memory.label} className={`memory-card ${memory.kind} tone-${memory.tone} ${memory.image ? "has-image" : ""}`} onClick={() => setGalleryIndex(i)} aria-label={`Open ${memory.label}`}>
          {memory.image && memory.kind !== "video" && <img className="memory-image w-full h-full object-cover absolute inset-0" src={memory.image} alt={memory.title} />}
          {memory.image && memory.kind === "video" && <video className="memory-image w-full h-full object-cover absolute inset-0" src={memory.image} autoPlay loop muted playsInline aria-label={memory.title} />}
          <span className="media-label">{memory.kind === "video" ? "▶ video" : memory.label}</span><div className="memory-copy"><strong>{memory.title}</strong>{memory.caption && <small>{memory.caption}</small>}</div></button>)}</div><p className="gallery-note">Six photographs and one moving memory, kept here for us.</p></section>
    <section className="love-section section-dark"><div className="section-intro"><SectionLabel>A growing list</SectionLabel><h2>Things I love<br /><em>about you.</em></h2><p>Tap through. Though, honestly, we both know six is not enough.</p></div><div className="love-card"><div className="love-number">{loveNotes[loveIndex][0]} <span>/ 06</span></div><div className="love-content"><h3>{loveNotes[loveIndex][1]}</h3><p>“{loveNotes[loveIndex][2]}”</p></div><div className="love-controls"><button onClick={() => setLoveIndex((loveIndex + loveNotes.length - 1) % loveNotes.length)} aria-label="Previous reason"><ArrowLeft size={18} /></button><div className="progress"><span style={{ width: `${progress}%` }} /></div><button onClick={() => setLoveIndex((loveIndex + 1) % loveNotes.length)} aria-label="Next reason"><ArrowRight size={18} /></button></div></div><div className="hidden-heart heart-one"><button onClick={() => setBaby(true)} aria-label="Reveal a hidden message"><Heart fill="currentColor" size={16} /></button>{baby && <span>My babyyyyyy 😂❤️<small>Yes, I know it sounds cuter when you say it.</small></span>}</div></section>
    <section className="play-section section-blush"><div className="play-grid"><div><SectionLabel>A very serious question</SectionLabel><h2>Have you<br /><em>eaten?</em></h2><p>Actually… never mind.<br />She probably hasn't. 😂</p><button className="outline-button" onClick={() => setHungry(!hungry)}>{hungry ? "Sugar needs fuel." : "Check on Lami"}</button>{hungry && <p className="play-reveal">Capri-Sun / juice to the rescue. 😂</p>}</div><div className="oko-card"><Sparkles size={20} /><p>There is something you occasionally call me…</p><button onClick={() => setOko(!oko)}>{oko ? "OKO MI 😂" : "Reveal it"}</button>{oko && <small>Madam, you still haven't made it official.</small>}</div></div></section>
    <section className="simple-section section-light"><SectionLabel>Our little things</SectionLabel><h2>It doesn't have<br /><em>to be complicated.</em></h2><div className="simple-list"><span>Holding hands.</span><span>Hugs.</span><span>Being together.</span><span>Sometimes doing absolutely nothing.</span></div><p>Our relationship does not need extravagant activities to be meaningful.</p></section>
    <section className="care-section section-cream"><div className="care-quote"><span>“</span><p>There was a time during my service year in Nasarawa when I misplaced the last money I had.</p><p>I remember telling you. And you sent me money to eat.</p><p>What still stays with me isn't just that you helped me. It is that you did it even when you didn't exactly have plenty for yourself.</p><strong>That meant more to me than you probably realised.</strong></div></section>
    <section id="letter" className="letter-section section-blush"><div className="letter-paper"><SectionLabel>From Timi, with all my heart</SectionLabel><h2>A letter<br /><em>to my Lami.</em></h2><div className="letter-body"><p>My Lami,</p><p>Somehow, the story of us begins all the way back in 2021, at Glory Arena in Redemption City. We met, became friends, and stayed friends for years. Looking back now, I think I was already becoming very attached to you before either of us had the sense to call it anything else.</p><p>I did make the first move. 😂 You just didn't take me seriously and left me comfortably sitting in the friend zone. Then came 2023: NYSC, three weeks of camp, and a cinema date that was supposed to be in the afternoon. You came late, we missed the original time, and somehow ended up watching <em>A Tribe Called Judah</em> late at night. My first cinema experience — with you. I still smile about it.</p><p>Then September 6, 2025 happened: Redemption City, trekking together, no grand plan, just us. And the next day, September 7, you said yes. My friend became my girl.</p><p>Since then, I have kept finding more things to love: your smile, your scent, your intelligence, your voice, your singing, and the fact that you are genuinely a keeper. I love when you call me “Oko mi” and “My babyyyyyy,” even if it sounds much cuter when you say it. I love that you have been there through meaningful seasons of my life. I remember Nasarawa, when you sent me money to eat even though you didn't have plenty for yourself. I remember your 25th birthday surprise too. These things stay with me.</p><p>Thank you for being my friend first, and my love now. I want to keep showing up for you, keep being there, and keep doing this life with you — with all the laughter, ordinary moments, and Capri-Sun rescues along the way.</p><p className="letter-end">Happy first anniversary, Sugar.<br />I love you.<br /><strong>— Timi</strong></p></div></div></section>
    <section className="future-section section-wine"><div className="section-center"><SectionLabel>What I hope for</SectionLabel><h2>Future<br /><em>with you.</em></h2><div className="future-lines"><Reveal>I don't just want more anniversaries with you.</Reveal><Reveal>I want ordinary Tuesdays.</Reveal><Reveal>I want mornings where you're the woman beside me.</Reveal><Reveal>I want us doing life together.</Reveal><Reveal>I want us making headways together.</Reveal><Reveal>I want us growing together.</Reveal><Reveal>I want us laughing together.</Reveal><Reveal>I want us holding hands through the good days.</Reveal><Reveal>And through the difficult days that will eventually come.</Reveal><Reveal>I want us to learn how to choose each other even then.</Reveal>{futureHopeLines.map(line => <Reveal key={line}>{line}</Reveal>)}</div><div className="future-choose"><p>My earnest desire is that you become the woman I wake up beside every day. I want to grow old with you.</p><span>If I get to choose who I walk into the future with…</span><strong>I choose you.</strong></div></div></section>
    <section className="promise section-dark"><SectionLabel>A simple promise</SectionLabel><h2>I'll always<br /><em>be there.</em></h2><p>No matter what.</p></section>
    <section id="ending" className="ending section-dark"><div className="ending-orb" /><SectionLabel>One last thing…</SectionLabel><div className="ending-lines"><p>Thank you for saying yes.</p><p>Thank you for being my friend first.</p><p>Thank you for becoming my love.</p><p>Thank you for being my Sugar.</p><p>Thank you for being my Lami.</p></div><div className="final-reveal"><Heart fill="currentColor" size={25} /><h2>Happy 1st<br /><em>Anniversary.</em></h2><p>September 7, 2026</p><strong>Forever sounds better when I imagine it with you.</strong><span>Timi</span></div><div className="hidden-heart ending-heart"><button onClick={() => setBaby(!baby)} aria-label="Reveal the final easter egg"><Heart fill="currentColor" size={13} /></button>{baby && <span>P.S. I still think you took too long to say yes. 😂❤️</span>}</div></section>
  </main><div className="music-player" role="region" aria-label="Music player"><audio ref={audioRef} src="/Iyawomi.mp3" loop /><Music2 size={17} /><div><strong>Iyawo Mi</strong><small>Timi Dakolo</small></div><button onClick={() => setIsPlaying(!isPlaying)} aria-label={isPlaying ? "Pause music" : "Play music"}>{isPlaying ? <Pause size={15} /> : <Play size={15} />}</button><button onClick={() => setIsMuted(!isMuted)} aria-label={isMuted ? "Unmute music" : "Mute music"}>{isMuted ? <VolumeX size={15} /> : <Volume2 size={15} />}</button></div>{galleryIndex !== null && <div className="lightbox" role="dialog" aria-modal="true" aria-label="Memory viewer" aria-describedby="memory-viewer-title"><button ref={lightboxCloseRef} className="lightbox-close" onClick={() => setGalleryIndex(null)} aria-label="Close viewer"><X /></button><button className="lightbox-arrow left" onClick={() => setGalleryIndex((galleryIndex + memories.length - 1) % memories.length)} aria-label="Previous memory"><ArrowLeft /></button><div className={`lightbox-art tone-${memories[galleryIndex].tone}`}>{memories[galleryIndex].kind === "video" ? <video className="lightbox-video" controls preload="metadata" src={memories[galleryIndex].image} aria-label={memories[galleryIndex].title} /> : memories[galleryIndex].image ? <img className="lightbox-image" src={memories[galleryIndex].image} alt={memories[galleryIndex].title} /> : <div className="lightbox-empty">Add this memory when its photo is available.</div>}<div className="lightbox-copy"><span>{memories[galleryIndex].label}</span><strong id="memory-viewer-title">{memories[galleryIndex].title}</strong><small>{memories[galleryIndex].kind === "video" ? "Press play to revisit this moving memory" : "Use left and right arrow keys to browse"}</small></div></div><button className="lightbox-arrow right" onClick={() => setGalleryIndex((galleryIndex + 1) % memories.length)} aria-label="Next memory"><ArrowRight /></button></div>}</div>;
}
